# Pre-commit configuration for PPA Contatto Home Assistant Integration
# See https://pre-commit.com for more information

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--check", "--diff", "--color", "--line-length=120"]
        files: ^custom_components/.*\.py$
